-- MySQL Script generated by MySQL Workbench
-- 02/10/16 16:06:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`goods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`goods` (
  `good_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `good_name` VARCHAR(45) NOT NULL,
  `price` FLOAT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  `goodscol` VARCHAR(45) NULL,
  PRIMARY KEY (`good_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`type_goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type_goods` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type_goods` (
  `good_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `good_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`good_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`attributs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`attributs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`attributs` (
  `attribut_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `attribut_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`attribut_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`good_attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`good_attribute` ;

CREATE TABLE IF NOT EXISTS `mydb`.`good_attribute` (
  `good_attribute_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `good_id` SMALLINT UNSIGNED NOT NULL,
  `attribut_id` SMALLINT UNSIGNED NOT NULL,
  `value` VARCHAR(45) NULL,
  PRIMARY KEY (`good_attribute_id`, `good_id`, `attribut_id`),
  INDEX `fk_good_attribute_goods1_idx` (`good_id` ASC),
  INDEX `fk_good_attribute_attributs1_idx` (`attribut_id` ASC),
  CONSTRAINT `fk_good_attribute_goods1`
    FOREIGN KEY (`good_id`)
    REFERENCES `mydb`.`goods` (`good_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_good_attribute_attributs1`
    FOREIGN KEY (`attribut_id`)
    REFERENCES `mydb`.`attributs` (`attribut_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`shop` ;

CREATE TABLE IF NOT EXISTS `mydb`.`shop` (
  `inventory_number` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `good_id` SMALLINT UNSIGNED NOT NULL,
  `date_come` DATETIME NOT NULL,
  PRIMARY KEY (`inventory_number`, `good_id`),
  INDEX `fk_shop_goods1_idx` (`good_id` ASC),
  CONSTRAINT `fk_shop_goods1`
    FOREIGN KEY (`good_id`)
    REFERENCES `mydb`.`goods` (`good_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `customer_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `discount` TINYINT(2) UNSIGNED NULL,
  `phone` VARCHAR(13) NOT NULL,
  `role` VARCHAR(45) NULL DEFAULT 'user',
  `password` VARCHAR(45) NULL,
  `registration_date` TIMESTAMP NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`statuses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`statuses` (
  `status_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_date` TIMESTAMP NULL,
  `shop_inventory_number` SMALLINT UNSIGNED NOT NULL,
  `order_price` FLOAT UNSIGNED NULL,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `status_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `shop_inventory_number`, `customer_id`, `status_id`),
  INDEX `fk_orders_shop1_idx` (`shop_inventory_number` ASC),
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC),
  INDEX `fk_orders_statuses1_idx` (`status_id` ASC),
  CONSTRAINT `fk_orders_shop1`
    FOREIGN KEY (`shop_inventory_number`)
    REFERENCES `mydb`.`shop` (`inventory_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_statuses1`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydb`.`statuses` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`menus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`menus` (
  `menu_title` VARCHAR(45) NULL,
  `page_url` VARCHAR(45) NULL,
  `menu_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pages` (
  `page_title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `menu_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`menu_id`),
  CONSTRAINT `fk_pages_menus1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `mydb`.`menus` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
